version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  webserver:
    image: quay.io/astronomer/ap-airflow:2.3.0-buster
    env_file:
      - .env
    command: webserver
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/local/airflow
    environment:
      - LOAD_EXAMPLES=False

  scheduler:
    image: quay.io/astronomer/ap-airflow:2.3.0-buster
    env_file:
      - .env
    command: scheduler
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/local/airflow
    environment:
      - LOAD_EXAMPLES=False
